import { Inter } from "next/font/google";
import "./globals.css";
import 'aos/dist/aos.css';
import AOSInit from './components/AOSInit';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "task-1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
    <head>
      <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    </head>
    <body>
      <AOSInit />
      {children}
    </body>
  </html>
  );
}
